### ISSUE TITLE
Projects and Tasks Aren't Loading

### ISSUE THREAD

**Issue by jamesmusson** [lazyatom/freeagent-widget#10]
This looks like a great widget, very easy to use, but unfortunately I'm not able to get it to connect to my FreeAgent account.

I have entered my details, but when the front loads, the projects and tasks drop-downs remain blank and the timer displays ‘NaN:NaN:’.

I've tried:

• Verifying the domain, username and password.
• Re-installing the widget.

This is the console error message on load:

22/10/2009 10.18:46am   com.apple.Dock.agent[2399]  2009-10-22 10:18:46.848 DashboardClient[2948:a03] com.lazyatom.widget.FreeAgent: illegal type passed to setPreferenceForKey: undefined
22/10/2009 10.18:46am   DashboardClient[2948]   com.lazyatom.widget.FreeAgent: illegal type passed to setPreferenceForKey: undefined

Thank you very much in advance!

**Comment by shentonfreude** [comment]
I have the same problem on OS X 10.6.2 Snow Leopard.  I enter the domain, email, password and it can connect to FreeAgent when I click the right-arrow. But the left pulldown only has a blank entry with a checkmark, and the right pulldown is empty.

How can I help debug and fix this?

**Comment by shentonfreude** [comment]
When I let the timer run (with blank Project and Task), then hit POST, I see the following in the system.log:

Jan  4 12:25:35 asylum DashboardClient[86167]: (com.lazyatom.widget.FreeAgent) file:///Users/cshenton/Library/Widgets/FreeAgent%202.wdgt/free_agent.js: TypeError: Result of expression 'this.currentProject' [undefined] is not an object. (line: 100)
Jan  4 12:25:35 asylum com.apple.Dock.agent[46884]: 2010-01-04 12:25:35.126 DashboardClient[86167:a03](com.lazyatom.widget.FreeAgent) file:///Users/cshenton/Library/Widgets/FreeAgent%202.wdgt/free_agent.js: TypeError: Result of expression 'this.currentProject' [undefined] is not an object. (line: 100)

Strange: removed and re-added widget to dashboard, same behavior but now I don't see a checkmark next to the blank Project pulldown.

**Comment by shentonfreude** [comment]
I found that I had to go into FreeAgent "Settings" (top of the page) and Enable access to the API. Without this command line (e.g., curl) nor Widget access was authorized.  

Perhaps this will help others, maybe worth a note on your widget download page. 

Can I also suggest that you mention that "Domain" is just your my_company name, not my_company.freeagent.com.

**Comment by CLGolden** [comment]
I also had to search for the instruction to enable the API; obvious in retrospect. Nice looking widget. Thanks!

**Comment by lazyatom** [comment]
I've clarified the expected domain contents in version 1.3.5 (available in the downloads section). Thanks!
