### ISSUE TITLE
Timeslips aren't submitting

### ISSUE THREAD

**Issue by bensauer** [lazyatom/freeagent-widget#14]
Dunno if this is cos of the update, but this morning it stopped successfully submitting.

I could do with a big red error message telling me this (future edit?) as I might have missed it. 

Ta,

B

**Comment by lealea** [comment]
I'm am also having this problem. :-/ Alas!

**Comment by jfahrenkrug** [comment]
I'm having this problem as well.

**Comment by jfahrenkrug** [comment]
I have fixed this in my fork: http://github.com/jfahrenkrug/freeagent-widget

**Comment by lazyatom** [comment]
I've fixed this in master (based on jfahrenkrug's fix, although I couldn't directly use his commit). You can also grab the latest widget at http://public.lazyatom.com/FreeAgent-1.3.2.zip

**Comment by bensauer** [comment]
this started happening again today... is it just me?

**Comment by lealea** [comment]
ben, not just you. just noticed it right now.
