### ISSUE TITLE
Times not posting

### ISSUE THREAD

**Issue by kilncollective** [lazyatom/freeagent-widget#15]
Hi,

This app has been fabulous, thanks!

But, lately it hasn't been posting times to Freeagent. It seems to read my Freeagent account ok and shows me all my current projects. It loads new projects and task quickly.

One of the logs in Console is...

7/08/10 4:11:16 PM [0x0-0xb00b].com.apple.dock[198] 2010-08-07 16:11:16.443 DashboardClient[4685:10b](com.lazyatom.widget.FreeAgent) file:///Users/belinda/Library/Widgets/FreeAgent.wdgt/free_agent.js: TypeError: Result of expression 'this.currentTask' [null] is not an object. (line: 108) 

Not sure if that is relevant.

Thanks

**Comment by lazyatom** [comment]
Thanks for your report - the detail really helped. It turned out that there's a new (better) way of getting the UserID, which the widget now uses.

This should be fixed in 4d0ebda8fc00a5a5d156, and you can download it here: http://github.com/downloads/lazyatom/freeagent-widget/FreeAgent-1.3.3.zip

**Comment by kilncollective** [comment]
Thanks for the speedy response! 

I installed the new version of the widget but it doesn't do anything. It's completely frozen.

The only log in Console is....

9/08/10 12:09:33 PM Widget Installer[6938] CFBundleVersion must be a string 
9/08/10 12:09:33 PM [0x0-0xb00b].com.apple.dock[198] 2010-08-09 12:09:33.464 Widget Installer[6938:10b] CFBundleVersion must be a string
