### ISSUE TITLE
Not Recording Time

### ISSUE THREAD

**Issue by amlich** [lazyatom/freeagent-widget#17]
I have been using the widget for a while know to track projects, and for a couple months, I just have been to busy to look at my time online, and today I went to check the total time on a project and realized it hasn't been tracking!!! Is there a way to get a log of all that time or is it lost for good? Also why is it not working?

**Comment by lazyatom** [comment]
Sorry to hear that. I'm afraid that the timeslips which failed to post
are lost for good.

The larger issue is that I don't really use this widget anymore.
However, there is a patch for posting times that might fix the issue
in the future. I'll look into applying and this producing a new
release, but I can't guarantee any timescale unfortunately.

On 10 June 2011 20:19, amlich
reply@reply.github.com
wrote:

**Comment by lazyatom** [comment]
Hi - I've just tested my local copy of the widget, and it looks like it's posting successfully... can you re-confirm that it's not working for you?

**Comment by lazyatom** [comment]
Stale; closing.
