### ISSUE TITLE
nil user-id being supplied on POST

### ISSUE THREAD

**Issue by lylo** [lazyatom/freeagent-widget#2]
From the application log:

Apr 22 12:36:42 [25786] INFO:   Parameters: {"project_id"=>"6780", "timeslip"=>{"task_id"=>"4495", "dated_on"=>"Wed, 22 
Apr 2009 12:36:42 GMT", "user_id"=>"null", "hours"=>"0.0175"}, "action"=>"create", "controller"=>"timeslips"}

**Comment by lazyatom** [comment]
Hmm, because the project/task IDs are there, the authentication must be working, so it can't be that. This part works by asking the server for all users, and then finding one that matches the email you provided on the back of the widget. Does your email match the one that the FreeAgent API returns?

**Comment by lazyatom** [comment]
Let me know if you figured this out, hopefully it's something I can guard against.

**Comment by lylo** [comment]
I'm no longer seeing this issue since downloading the latest :)

**Comment by lazyatom** [comment]
Great :)
