### ISSUE TITLE
New task is not always created in FreeAgent

### ISSUE THREAD

**Issue by jhubb** [lazyatom/freeagent-widget#5]
Tasks even with simple names are not always created in FreeAgent, and sometimes there is a delay of a couple of minutes.

**Comment by lazyatom** [comment]
If this delay is not consistent, it could be problems with your network connection, or with FreeAgent's response time. Can you give examples of any tasks that consistently fail, or is this covered by your '&' tickets?

**Comment by lazyatom** [comment]
No feedback, so closing.
