### ISSUE TITLE
Does Not Post to FreeAgent

### ISSUE THREAD

**Issue by davidnicholson** [lazyatom/freeagent-widget#8]
Hi,

I  just got myself a new Mac (been using a PC for far too long..)... but i am having problems with the widget. It shows my projects and tasks but when i hit the "post" button nothing happens. 

I am not sure if this is a confrig issue with me being new to a Mac..

Best

David

**Comment by lazyatom** [comment]
I'm going to try and add some better debug information into the log - meanwhile, if you open Console.app (in /Applications/Utilities) and try posting from the widget, you should get some information. Could you post it here?

**Comment by lazyatom** [comment]
No feedback, so closing...
