### ISSUE TITLE
Posting fails

### ISSUE THREAD

**Issue by bensauer** [lazyatom/freeagent-widget#9]
Dunno what's up with it, its suddenly not loading data into the forms or able to post data. Is this because of the FAC upgrade the other day perhaps?

B

**Comment by lazyatom** [comment]
Let me know if it still doesn't work, even with API access enabled; otherwise I'll close this issue.

**Comment by bensauer** [comment]
I'll close, that was the issue. Offer feedback in the next version perhaps? Thanks for help.

**Comment by bensauer** [comment]
oh... hang on. Menus are loading, but it's not posting successfully.

**Comment by lazyatom** [comment]
I'm uploading a new (1.3) release soon (just waiting for DNS to resolve), but you can grab the latest code from here if you have Dashcode installed - I'm curious to see if it helps your problem.

**Comment by lazyatom** [comment]
Get the latest version here: http://public.lazyatom.com/FreeAgent-1.3.0.zip

**Comment by bensauer** [comment]
thanks for correction, whatever it was. Working now! One tiny thing: the default time that displayed was something weird like: "NaNaNa".

**Comment by lazyatom** [comment]
Does it still show that, after at a successful post? Btw, please update to [1.3.1](http://public.lazyatom.com/FreeAgent-1.3.1.zip)

**Comment by bensauer** [comment]
I've updated. Seems fine now.

**Comment by lazyatom** [comment]
Awesome :)
